### ISSUE TITLE
Create a known products list to be used within the platform

### ISSUE THREAD

**Issue by AlexandreSSJr** [emilrb/bia-server#7]
**Description:**

We need to gather all information from each available item already displayed in existing Forms, possibly including new fields to characterize each item.

**For example:**
EAN
ANVISA Code

**Comment by carloselborges** [comment]
We need to create also a measurement unity crud.

**Comment by esganzerla** [comment]
From the tab `0.Consolidade_BOLETIM`, I found these:

```
'Unidade(s)',
'Caixa(s) com 50',
'Caixa(s) com 100',
'Litro(s)',
'Sache(s)',
```

Are there more places we should be looking at?

**Comment by esganzerla** [comment]
I believe it's done. We just need to check what's the most accurate source of these data.
